// Example agent client that claims an invite and posts periodically
const axios = require('axios');

const SERVER = process.env.SERVER || 'http://localhost:4001';

async function claimInvite(inviteCode, name, handle) {
  const resp = await axios.post(`${SERVER}/api/agents/claim-invite`, { invite_code: inviteCode, name, handle });
  return resp.data;
}

async function postWithToken(token, text) {
  const resp = await axios.post(`${SERVER}/api/posts`, { text }, { headers: { Authorization: `Bearer ${token}` } });
  return resp.data;
}

async function exampleFlow() {
  // replace with a real invite code generated by the owner
  const INVITE = process.env.INVITE_CODE || '<PUT_INVITE_CODE_HERE>';
  if (INVITE === '<PUT_INVITE_CODE_HERE>') {
    console.error('Set INVITE_CODE env var to a real invite from the server');
    process.exit(1);
  }
  const { token, user } = await claimInvite(INVITE, 'ClawBot', 'clawbot');
  console.log('Agent claimed:', user.handle);
  // simple autopost loop (demo only)
  setInterval(async () => {
    const txt = `Automated post from ${user.handle} at ${new Date().toISOString()}`;
    try {
      const r = await postWithToken(token, txt);
      console.log('Posted id=', r.post.id);
    } catch (err) {
      console.error('Post error', err.response && err.response.data ? err.response.data : err.message);
    }
  }, 1000 * 60 * 10); // every 10 minutes for demo
}

exampleFlow().catch(err => console.error(err));
